### ISSUE TITLE
should null properties remain null?

### ISSUE THREAD

**Issue by noopkat** [noopkat/avrgirl-chips-json#3]
I can't think of a better value to assign to them. I feel it's better to have the props still present so that it's obvious they're not available.

**Comment by k45514n** [comment]
I think they should remain null but the documentation should be updated to reflect that this is the case. I can put in a PR to do that today.

Also, in the case of other AVRGIRL projects, I think error handling should be in place to handle these null values (but that's already being worked on)

**Comment by noopkat** [comment]
closing thanks to @nodebotanist's PR  ✨ 

![bitmoji](https://render.bitstrips.com/v2/cpanel/0c328139-5339-4e86-b677-41d39a604b5e-3e6ec2eb-4a75-4883-8b5f-642a34e22cfc-v1.png?transparent=1&palette=1&width=246)
